# Disclaimer Policy Configuration
# Defines thresholds and sensitive topics for the core system

disclaimer_policy:
  # Quality thresholds for content filtering
  quality_thresholds:
    minimum_qa_score: 0.7
    minimum_confidence: 0.8
    
  # Sensitive topics that require special handling
  sensitive_topics:
    - "criminal law"
    - "tax evasion"
    - "immigration violations"
    - "financial fraud"
    - "personal injury claims"
    - "medical malpractice"
    - "employment discrimination"
    - "family law disputes"
    
  # Content moderation rules
  moderation:
    auto_approve_threshold: 0.9
    manual_review_threshold: 0.7
    auto_reject_threshold: 0.3
    
  # PII handling
  pii_policy:
    allowed_pii_types: []
    require_anonymization: true
    retention_period_days: 365
    
  # Legal disclaimers
  disclaimers:
    general: "This information is for educational purposes only and does not constitute legal advice."
    sensitive: "This content involves sensitive legal matters. Please consult with a qualified attorney."
    ai_generated: "This response was generated by AI and should be verified by legal professionals."
